from google import genai
from google.genai.types import HttpOptions
from google.genai import types
from google.cloud import language_v2
from langsmith import traceable

@traceable
async def create_draft_reply (email_text: str) -> str:
    """
    Generates a helpful, brand-aligned draft reply template for a customer email
    using the Google Gemini 2.0 Flash model.

    This function constructs a detailed prompt that instructs the AI to act as
    a customer support agent from the Otto Group, emphasizing brand alignment
    and strict avoidance of Personal Identifiable Information (PII) in the
    generated reply. It then sends this prompt, along with the customer's
    original email text, to the `gemini-2.0-flash-001` model via the
    Google Generative AI client.

    The model's response, which is the drafted reply, is returned as a string.

    Args:
        email_text (str): The full content of the customer's original email,
                          which the AI will use as context to generate the reply.

    Returns:
        str: A brand-aligned, PII-free draft reply template generated by the
             Gemini model.
    """
    draft_prompt = f"""You are a customer support agent.
    You are generating a brand-aligned draft reply template from the Otto Group in response to a customer message.
    Do not include any personal information about the customer in the template.

    Here is the customer's original email:
    ---
    {email_text}
    ---

    Based on all this information, please write a draft reply.
    """
    client = genai.Client(
        http_options=HttpOptions(api_version="v1"), 
        vertexai=True,
        project="ogcs-av8t-ailaboratory",
        location="europe-west1"
    )
    response = await client.aio.models.generate_content(
        model='gemini-2.0-flash-001',
        contents= draft_prompt,

    )
    return response.text
